/* ============================================================
   Massage 4 Beauty — site content in 3 languages.
   Edit text and prices here. Prices are numbers (CZK).
   ============================================================ */
window.CONTENT = {
  contact: {
    address: "Děkanská vinice I 819/16, Praha 4 – Nusle",
    phone: "+420 721 761 411",
    email: "beautymassage.prague@gmail.com",
  },

  /* -------------------- ENGLISH -------------------- */
  en: {
    currency: (p) => p.toLocaleString("en-US").replace(/,/g, "\u00a0") + "\u00a0CZK",
    minLabel: "min",
    strings: {
      navServices: "Services", navPrices: "Price list", navAbout: "About", navContact: "Contact",
      heroEyebrow: "Massage 4 Beauty · Prague",
      heroH1: "Professional massage studio in Prague 4",
      heroSub: "Healthy, glowing skin begins with a gentle touch. Facial and body massage by Ludmila — over ten years of experience, personalised techniques, visible results.",
      ctaBook: "Book an appointment", ctaPrices: "View price list",
      aboutEyebrow: "About the master", aboutName: "Ludmila Yemelianova",
      aboutWelcome: "Welcome to Massage 4 Beauty.",
      aboutP1: "My name is Ludmila, and for over ten years I have been helping my clients find harmony, relaxation and natural beauty through professional facial and body massage.",
      aboutP2: "Every treatment is unique and tailored to your individual needs. Whether you are looking for deep relaxation, relief from tension, body recovery or natural skin rejuvenation, together we will find the care that is right for you.",
      aboutP3: "My goal is that after your treatment you leave not only feeling light and rested, but also with renewed energy, healthier skin and a greater sense of harmony between body and soul.",
      aboutCaption: "Certified massage therapist · Prague",
      pricesEyebrow: "Price list", pricesH2: "Treatments & pricing",
      groupFace: "Face", groupBody: "Body",
      contactEyebrow: "Contact", contactH2: "Book your visit",
      contactSub: "Leave a message and we'll help you pick the right treatment and a convenient date and time.",
      lblAddress: "Address", lblPhone: "Phone", lblEmail: "Email",
      fName: "Your name", fContact: "Phone or email", fTreatment: "Treatment (optional)", fMessage: "Message", fSend: "Send request",
      formThanks: "Thank you! We'll get back to you shortly.",
      footerCopy: "© 2026 Beauty Massage by Ludmila Yemelianova",
      privacyLink: "Privacy Policy",
      privacyEyebrow: "Legal information",
      privacyH1: "Privacy Policy (GDPR)",
      privacyEffective: "Effective from 15 September 2026",
      privacyIntro: "This policy explains what personal data we process when you visit beautymassage.cz, send us a booking request or contact us in another way, and what rights you have.",
      privacyH2Controller: "1. Who processes your data",
      privacyController: "The data controller is Liudmyla Yemelianova, a self-employed sole trader, company ID (IČO) 23110716, registered at Karlínské náměstí 170/3, 186 00 Prague 8 – Karlín, Czech Republic. Under the Massage 4 Beauty brand she runs the studio at Děkanská vinice I 819/16, 140 00 Prague 4 – Nusle. For data protection questions, use the email or phone below.",
      privacyDpo: "We have not appointed a data protection officer, as we are not required to.",
      privacyH2Purposes: "2. What data we process and why",
      privacyDtData: "Data", privacyDtPurpose: "Purpose", privacyDtBasis: "Legal basis", privacyDtRetention: "Retention",
      privacyH3Booking: "Booking requests",
      privacyBookingData: "Name, phone or email, the chosen treatment and the message you write, plus anything from our phone or email conversations.",
      privacyBookingPurpose: "Replying to your request, arranging an appointment and providing the massage.",
      privacyBookingBasis: "Steps taken at your request before a contract, and performance of the contract (Art. 6(1)(b) GDPR).",
      privacyBookingRetention: "If no appointment follows, we delete the data no later than 12 months after our last contact. For clients we keep it for as long as we work together and no longer than 3 years after the last visit; tax records for as long as the law requires.",
      privacyBookingNote: "Please don't include health information in the form. We discuss any health limitations in person before the massage.",
      privacyH3Spam: "Protecting the form from spam",
      privacySpamData: "IP address and technical details of your browser and device when the form is sent.",
      privacySpamPurpose: "Checking that a person is sending the form, and protecting us from spam.",
      privacySpamBasis: "Our legitimate interest in protecting the form from misuse (Art. 6(1)(f) GDPR).",
      privacySpamRetention: "Cloudflare processes the data only for as long as the check takes.",
      privacyH3Photos: "Photos",
      privacyPhotosData: "Photos or videos from the treatment.",
      privacyPhotosPurpose: "Showing our work on the website and the studio's social media.",
      privacyPhotosBasis: "Your consent (Art. 6(1)(a) GDPR), given in person or in writing.",
      privacyPhotosRetention: "Until you withdraw consent. We then remove the photos from the website and our profiles.",
      privacyH3Marketing: "News and offers",
      privacyMarketingData: "Email address or phone number.",
      privacyMarketingPurpose: "Sending news, offers and available dates by email or SMS.",
      privacyMarketingBasis: "Your consent (Art. 6(1)(a) GDPR).",
      privacyMarketingRetention: "Until you withdraw consent, and no longer than 3 years after our last contact.",
      privacyH3Analytics: "Website analytics",
      privacyAnalyticsData: "Pages visited, clicks on booking, phone and email buttons, sent booking requests (without their content), device and browser type, approximate location, and online identifiers in cookies. Google Analytics 4 does not store your IP address.",
      privacyAnalyticsPurpose: "Understanding how the website is used and which pages lead to bookings, so we can improve it.",
      privacyAnalyticsBasis: "Your consent in the cookie banner (Art. 6(1)(a) GDPR and Section 89(3) of Czech Act No. 127/2005 Coll., on Electronic Communications).",
      privacyAnalyticsRetention: "Up to 14 months.",
      privacyAnalyticsNote: "Until you give consent, Google Analytics stores no cookies or identifiers and receives only limited signals that are not linked to your device (Google Consent Mode).",
      privacyH3Hosting: "Running the website",
      privacyHostingData: "IP address and technical details of your browser and request. The site's fonts load from Google Fonts, so opening a page also sends your IP address to Google.",
      privacyHostingPurpose: "Delivering the website and its fonts, and protecting the site against attacks.",
      privacyHostingBasis: "Our legitimate interest in running the website securely and reliably (Art. 6(1)(f) GDPR).",
      privacyHostingRetention: "Technical logs are kept briefly, according to the providers' settings.",
      privacyH2Recipients: "3. Who we share data with",
      privacyRecipientsIntro: "We don't sell your data. These processors and service providers help us handle it:",
      privacyRecipient1: "Cloudflare, Inc. (USA) — website hosting, security and form protection (Turnstile).",
      privacyRecipient2: "Google Ireland Limited / Google LLC — Google Analytics, Google Fonts and email (Gmail).",
      privacyRecipient3: "Telegram FZ-LLC (United Arab Emirates) — notifications of new booking requests in the studio's messaging app.",
      privacyRecipientsAuthorities: "We may also share data with public authorities where the law requires it.",
      privacyH2Transfers: "4. Transfers outside the EU",
      privacyTransfers1: "Cloudflare and Google are certified under the EU-U.S. Data Privacy Framework, so transfers of data to these companies in the USA are covered by the European Commission's adequacy decision.",
      privacyTransfers2: "Telegram is based in the United Arab Emirates, for which no such decision exists. We send your booking request there because it is necessary to handle it (Art. 49(1)(b) GDPR). If you would rather we didn't, call us or email us instead of using the form.",
      privacyH2Storage: "5. Cookies and browser storage",
      privacyStorageIntro: "We always store what is strictly necessary, and analytics cookies only with your consent. If you decline or withdraw consent, analytics cookies are no longer set.",
      privacyStorage1: "m4b-cookies — your choice in the cookie banner (necessary, kept in your browser until deleted)",
      privacyStorage2: "m4b-lang — the selected website language (necessary, kept in your browser until deleted)",
      privacyStorage3: "_ga, _ga_XW10FL0HCW — Google Analytics cookies that distinguish visitors and visits (analytics, only with consent, 2 years)",
      privacyStorage4: "Cloudflare Turnstile — technical data needed to check that a person, not a bot, is sending the form (necessary)",
      privacyCookieSettings: "Change cookie settings",
      privacyH2Rights: "6. Your rights",
      privacyRightsIntro: "You have the right to:",
      privacyRight1: "access your data and get a copy of it,",
      privacyRight2: "have inaccurate data corrected,",
      privacyRight3: "have your data erased,",
      privacyRight4: "restrict processing,",
      privacyRight5: "receive your data in a machine-readable format,",
      privacyRight6: "object to processing based on legitimate interest,",
      privacyRight7: "withdraw consent at any time, without affecting processing carried out before you withdrew it.",
      privacyRightsHow: "Email us at beautymassage.prague@gmail.com. We reply without undue delay, and within one month at the latest.",
      privacyComplaint: "You can also lodge a complaint with the Czech Office for Personal Data Protection (Úřad pro ochranu osobních údajů), Pplk. Sochora 727/27, 170 00 Prague 7 (uoou.gov.cz).",
      privacyH2Automated: "7. Automated decision-making",
      privacyAutomated: "We don't use automated decision-making or profiling with legal or similarly significant effects. Cloudflare Turnstile only checks automatically that the form isn't being sent by a bot; if the check fails, call or email us.",
      privacyH2Changes: "8. Changes to this policy",
      privacyChanges: "We may update this policy, for example when we change the services we use. The current version, with its effective date, is always on this page.",
      cookieText: "This website uses cookies to enhance your browsing experience. Please choose your preference below.",
      cookieAccept: "Accept", cookieDecline: "Decline", cookieMore: "Privacy Policy",
      crumbHome: "Home",
      crumbServices: "Massages",
      svcPhotoPlaceholder: "Banner goes here · 1920 × 800",
      svcFactDurationK: "Duration",
      svcFactPriceK: "Price",
      svcFactPlaceK: "Where",
      svcBookBtn: "Book an appointment",
      pricesHubLink: "Read about every massage →",
      svcBookBtn2: "Book an appointment",
      voucherLabel: "GIFT VOUCHER",
      orderCta: "Order",
      formError: "Something went wrong. Please try again or call us directly.",
      orderAria: "Order",
      voucherEyebrow: "A GIFT",
      voucherH: ["A moment of peace", "for the loved ones"],
      voucherHomeH2: "Gift voucher",
      voucherHomeText: "Give an hour of calm to someone close. Choose a treatment or an amount — the voucher arrives by e-mail within 24 hours and is valid for 12 months.",
      voucherCta: "Order the voucher",
      voucherMore: "About the voucher",
      fVoucherOption: "Gift voucher",
    },
    facial: [
      { name: "Facial Ritual — Neck, Décolleté, Face & Head", desc: "A deep, multi-level procedure releasing muscle tension, improving blood and lymph circulation, and naturally restoring skin tone.", min: 60, price: 1600 },
      { name: "Facial Lymphatic Massage", desc: "Very gentle drainage that clears puffiness, reduces under-eye bags and sharpens the contours of the face.", min: 45, price: 1000 },
      { name: "Myofascial Facial Massage", desc: "Intensive work with facial muscles, including the inner cheek area. Sculpts the contour, reduces nasolabial folds and sagging.", min: 45, price: 1300 },
      { name: "Neck, Décolleté & Hands Massage", desc: "Improves blood flow and lymph drainage while relaxing the muscles of the neck and chest area.", min: 60, price: 1200 },
      { name: "Lifting Massage", desc: "Reduces puffiness under the eyes, improves lymphatic drainage, gives the face a lighter, more lifted appearance.", min: 45, price: 1000 },
      { name: "Vacuum (Cupping) Facial Massage", desc: "Focuses on muscle toning and strengthening, enhancing skin elasticity and facial contours.", min: 45, price: 800 },
      { name: "Gua Sha Massage", desc: "A draining, contouring treatment that relieves tension and enhances skin tone using traditional Gua Sha techniques.", min: 45, price: 800 },
      { name: "Buccal Massage", desc: "A facial massage technique performed both externally and through the oral cavity. Helps relieve facial muscle tension, improve microcirculation, increase skin tone and define facial contours. Promotes natural rejuvenation and deep relaxation.", min: 30, price: 800 },
      { name: "Alginate Mask · add-on", desc: "Reduces swelling and redness, evens out skin tone, deeply moisturises and soothes the skin.", min: 15, price: 250 },
      { name: "Head Massage", desc: "Relaxes the nervous system, stimulates hair growth, reduces stress and helps prevent headaches.", min: 30, price: 600 },
    ],
    body: [
      { name: "Sports Massage", desc: "Muscle recovery after exertion and intense training — relieves tension, reduces soreness, speeds up recovery.", min: 60, price: 1600 },
      { name: "Massage with Bamboo Brooms", desc: "The body is gently warmed and massaged with bamboo brooms, improving circulation, lymph flow and skin tone.", min: 60, price: 1600 },
      { name: "Lymphatic Drainage Massage", desc: "Improves lymph flow, reduces swelling and puffiness, supports metabolism and overall well-being.", min: 60, price: 1500 },
      { name: "Anti-Cellulite Massage", desc: "Intensive work on problem areas — improves circulation, stimulates fat breakdown, increases skin firmness.", min: 45, price: 1500 },
      { name: "Honey Massage", desc: "Natural honey cleanses the skin and activates metabolism, leaving skin smoother, softer and refreshed.", min: 60, price: 1500 },
      { name: "Classic Massage", desc: "A universal procedure for relaxation and overall wellness — improves circulation and restores energy.", min: 60, price: 1300 },
      { name: "Aroma Massage", desc: "Classic techniques with individually selected essential oils — deeply relaxing, lowers stress, improves mood.", min: 60, price: 1300 },
      { name: "Vacuum (Cupping) Body Massage", desc: "Suction cups actively stimulate blood and lymph circulation — reduces swelling, fights cellulite.", min: 45, price: 1200 },
      { name: "Back Massage", desc: "Relieves tension in the back muscles, reduces pain and fatigue, improves circulation and brings deep relaxation and a sense of lightness in the body.", min: 30, price: 700 },
      { name: "Reflexology Foot Massage", desc: "A technique targeting biologically active points and zones connected to internal organs and body systems. Stimulation of these points activates natural regeneration processes and overall relaxation.", min: 30, price: 600 },
    ],
  },

  /* -------------------- ČEŠTINA -------------------- */
  cs: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\s/g, "\u00a0") + "\u00a0Kč",
    minLabel: "min",
    strings: {
      navServices: "Služby", navPrices: "Ceník", navAbout: "O mně", navContact: "Kontakt",
      heroEyebrow: "Massage 4 Beauty · Praha",
      heroH1: "Profesionální masážní studio Praha 4",
      heroSub: "Zdravá, zářivá pleť začíná jemným dotekem. Relaxační masáže v příjemném prostředí, které pomáhají uvolnit tělo, mysl i každodenní stres.",
      ctaBook: "Objednat se", ctaPrices: "Zobrazit ceník",
      aboutEyebrow: "O mně", aboutName: "Ludmila Yemelianova",
      aboutWelcome: "Vítejte v Massage 4 Beauty.",
      aboutP1: "Jmenuji se Ludmila a již více než deset let pomáhám svým klientům nacházet harmonii, relaxaci a přirozenou krásu prostřednictvím profesionálních masáží obličeje a těla.",
      aboutP2: "Každá procedura je jedinečná a přizpůsobena vašim individuálním potřebám. Ať hledáte hlubokou relaxaci, úlevu od napětí, regeneraci organismu nebo přirozené omlazení pleti, společně vybereme péči, která je určena přímo pro vás.",
      aboutP3: "Mým cílem je, abyste po proceduře odcházeli nejen s pocitem lehkosti a odpočinku, ale také s novou energií, zdravější pletí a větší harmonií těla i duše.",
      aboutCaption: "Certifikovaná masérka · Praha",
      pricesEyebrow: "Ceník", pricesH2: "Procedury a ceny",
      groupFace: "Obličej", groupBody: "Tělo",
      contactEyebrow: "Kontakt", contactH2: "Objednejte se",
      contactSub: "Napište nám a pomůžeme vám vybrat vhodnou proceduru i termín návštěvy.",
      lblAddress: "Adresa", lblPhone: "Telefon", lblEmail: "E-mail",
      fName: "Vaše jméno", fContact: "Telefon nebo e-mail", fTreatment: "Procedura (volitelné)", fMessage: "Zpráva", fSend: "Odeslat poptávku",
      formThanks: "Děkujeme! Brzy se vám ozveme.",
      footerCopy: "© 2026 Beauty Massage · Ludmila Yemelianova",
      privacyLink: "Ochrana osobních údajů",
      privacyEyebrow: "Právní informace",
      privacyH1: "Ochrana osobních údajů (GDPR)",
      privacyEffective: "Účinné od 15. září 2026",
      privacyIntro: "Tyto zásady vysvětlují, jaké osobní údaje zpracováváme, když navštívíte web beautymassage.cz, pošlete nám poptávku nebo nás jinak kontaktujete, a jaká máte práva.",
      privacyH2Controller: "1. Kdo zpracovává vaše údaje",
      privacyController: "Správcem osobních údajů je Liudmyla Yemelianova, fyzická osoba podnikající, IČO 23110716, se sídlem Karlínské náměstí 170/3, 186 00 Praha 8 – Karlín. Pod značkou Massage 4 Beauty provozuje studio na adrese Děkanská vinice I 819/16, 140 00 Praha 4 – Nusle. S dotazy k ochraně údajů se obraťte na e-mail nebo telefon níže.",
      privacyDpo: "Pověřence pro ochranu osobních údajů jsme nejmenovali, protože to pro nás není povinné.",
      privacyH2Purposes: "2. Jaké údaje zpracováváme a proč",
      privacyDtData: "Údaje", privacyDtPurpose: "Účel", privacyDtBasis: "Právní základ", privacyDtRetention: "Doba uložení",
      privacyH3Booking: "Poptávka a rezervace",
      privacyBookingData: "Jméno, telefon nebo e-mail, zvolená procedura a zpráva, kterou nám napíšete, případně údaje z naší komunikace telefonem nebo e-mailem.",
      privacyBookingPurpose: "Odpovědět na poptávku, domluvit termín a poskytnout masáž.",
      privacyBookingBasis: "Jednání o smlouvě na vaši žádost a plnění smlouvy (čl. 6 odst. 1 písm. b) GDPR).",
      privacyBookingRetention: "Pokud se rezervace neuskuteční, údaje smažeme nejpozději 12 měsíců od poslední komunikace. Klientům je uchováváme po dobu spolupráce a nejdéle 3 roky od poslední návštěvy; daňové doklady po dobu, kterou ukládá zákon.",
      privacyBookingNote: "Do formuláře prosím nepište údaje o svém zdraví. Případná zdravotní omezení probereme osobně před masáží.",
      privacyH3Spam: "Ochrana formuláře před spamem",
      privacySpamData: "IP adresa a technické údaje o prohlížeči a zařízení při odeslání formuláře.",
      privacySpamPurpose: "Ověřit, že formulář odesílá člověk, a chránit nás před spamem.",
      privacySpamBasis: "Oprávněný zájem na ochraně formuláře před zneužitím (čl. 6 odst. 1 písm. f) GDPR).",
      privacySpamRetention: "Cloudflare údaje zpracovává jen po dobu nutnou k ověření.",
      privacyH3Photos: "Fotografie",
      privacyPhotosData: "Fotografie nebo videa z procedury.",
      privacyPhotosPurpose: "Ukázky práce na webu a sociálních sítích studia.",
      privacyPhotosBasis: "Váš souhlas (čl. 6 odst. 1 písm. a) GDPR), který udělujete osobně nebo písemně.",
      privacyPhotosRetention: "Do odvolání souhlasu. Poté fotografie odstraníme z webu a z našich profilů.",
      privacyH3Marketing: "Novinky a nabídky",
      privacyMarketingData: "E-mail nebo telefonní číslo.",
      privacyMarketingPurpose: "Posílat novinky, nabídky a volné termíny e-mailem nebo SMS.",
      privacyMarketingBasis: "Váš souhlas (čl. 6 odst. 1 písm. a) GDPR).",
      privacyMarketingRetention: "Do odvolání souhlasu, nejdéle 3 roky od poslední komunikace.",
      privacyH3Analytics: "Analytika návštěvnosti",
      privacyAnalyticsData: "Navštívené stránky, kliknutí na tlačítka rezervace, telefonu a e-mailu, odeslání poptávky (bez jejího obsahu), typ zařízení a prohlížeče, přibližná poloha a online identifikátory v cookies. Google Analytics 4 neukládá vaši IP adresu.",
      privacyAnalyticsPurpose: "Zjistit, jak web používáte a které stránky vedou k rezervaci, a web podle toho zlepšovat.",
      privacyAnalyticsBasis: "Váš souhlas v cookie liště (čl. 6 odst. 1 písm. a) GDPR a § 89 odst. 3 zákona č. 127/2005 Sb., o elektronických komunikacích).",
      privacyAnalyticsRetention: "Nejdéle 14 měsíců.",
      privacyAnalyticsNote: "Dokud souhlas neudělíte, Google Analytics neukládá cookies ani identifikátory a dostává jen omezené signály bez vazby na vaše zařízení (Google Consent Mode).",
      privacyH3Hosting: "Provoz webu",
      privacyHostingData: "IP adresa a technické údaje o prohlížeči a požadavku. Písma webu se načítají ze služby Google Fonts, takže při zobrazení stránky se vaše IP adresa předá také společnosti Google.",
      privacyHostingPurpose: "Doručit web a jeho písma a chránit web před útoky.",
      privacyHostingBasis: "Oprávněný zájem na bezpečném a spolehlivém provozu webu (čl. 6 odst. 1 písm. f) GDPR).",
      privacyHostingRetention: "Technické záznamy krátkodobě podle nastavení poskytovatelů.",
      privacyH2Recipients: "3. Komu údaje předáváme",
      privacyRecipientsIntro: "Údaje neprodáváme. Pomáhají nám s nimi tito zpracovatelé a poskytovatelé služeb:",
      privacyRecipient1: "Cloudflare, Inc. (USA) — hosting webu, zabezpečení a ochrana formuláře (Turnstile).",
      privacyRecipient2: "Google Ireland Limited / Google LLC — Google Analytics, Google Fonts a e-mail (Gmail).",
      privacyRecipient3: "Telegram FZ-LLC (Spojené arabské emiráty) — upozornění na novou poptávku v komunikátoru studia.",
      privacyRecipientsAuthorities: "Údaje můžeme předat také orgánům veřejné moci, pokud to vyžaduje zákon.",
      privacyH2Transfers: "4. Předávání mimo EU",
      privacyTransfers1: "Společnosti Cloudflare a Google jsou certifikovány v rámci EU-U.S. Data Privacy Framework, takže pro předání údajů do USA těmto společnostem platí rozhodnutí Evropské komise o odpovídající úrovni ochrany.",
      privacyTransfers2: "Telegram sídlí ve Spojených arabských emirátech, pro které takové rozhodnutí neexistuje. Zprávu s vaší poptávkou tam předáváme, protože je to nezbytné pro vyřízení vaší žádosti (čl. 49 odst. 1 písm. b) GDPR). Pokud si to nepřejete, zavolejte nám nebo napište e-mail místo formuláře.",
      privacyH2Storage: "5. Cookies a úložiště v prohlížeči",
      privacyStorageIntro: "Nezbytné položky ukládáme vždy, analytické cookies jen s vaším souhlasem. Pokud souhlas odmítnete nebo odvoláte, analytické cookies se už neukládají.",
      privacyStorage1: "m4b-cookies — vaše volba v cookie liště (nezbytné, uloženo v prohlížeči do smazání)",
      privacyStorage2: "m4b-lang — zvolený jazyk webu (nezbytné, uloženo v prohlížeči do smazání)",
      privacyStorage3: "_ga, _ga_XW10FL0HCW — cookies Google Analytics k rozlišení návštěvníků a návštěv (analytické, jen se souhlasem, platnost 2 roky)",
      privacyStorage4: "Cloudflare Turnstile — technické údaje nezbytné k ověření, že formulář neodesílá robot (nezbytné)",
      privacyCookieSettings: "Změnit nastavení cookies",
      privacyH2Rights: "6. Vaše práva",
      privacyRightsIntro: "Máte právo:",
      privacyRight1: "získat přístup ke svým údajům a jejich kopii,",
      privacyRight2: "požadovat opravu nepřesných údajů,",
      privacyRight3: "požadovat výmaz údajů,",
      privacyRight4: "požadovat omezení zpracování,",
      privacyRight5: "získat své údaje ve strojově čitelném formátu,",
      privacyRight6: "vznést námitku proti zpracování na základě oprávněného zájmu,",
      privacyRight7: "kdykoli odvolat souhlas; zákonnost zpracování před odvoláním tím není dotčena.",
      privacyRightsHow: "Napište nám na beautymassage.prague@gmail.com. Odpovíme bez zbytečného odkladu, nejpozději do jednoho měsíce.",
      privacyComplaint: "Můžete také podat stížnost u Úřadu pro ochranu osobních údajů, Pplk. Sochora 727/27, 170 00 Praha 7 (uoou.gov.cz).",
      privacyH2Automated: "7. Automatizované rozhodování",
      privacyAutomated: "Nepoužíváme automatizované rozhodování ani profilování s právními nebo podobně závažnými účinky. Cloudflare Turnstile pouze automaticky ověřuje, zda formulář neodesílá robot; pokud ověření selže, zavolejte nám nebo napište e-mail.",
      privacyH2Changes: "8. Změny zásad",
      privacyChanges: "Zásady můžeme aktualizovat, například když změníme používané služby. Aktuální verze je vždy na této stránce i s datem účinnosti.",
      cookieText: "Tento web používá soubory cookie pro zlepšení vašeho zážitku z prohlížení. Vyberte prosím svou preferenci.",
      cookieAccept: "Přijmout", cookieDecline: "Odmítnout", cookieMore: "Ochrana osobních údajů",
      crumbHome: "Domů",
      crumbServices: "Masáže",
      svcPhotoPlaceholder: "Místo pro banner · 1920 × 800",
      svcFactDurationK: "Délka",
      svcFactPriceK: "Cena",
      svcFactPlaceK: "Kde",
      svcBookBtn: "Rezervovat termín",
      pricesHubLink: "Přečtěte si o každé masáži →",
      svcBookBtn2: "Rezervovat termín",
      voucherLabel: "DÁRKOVÝ POUKAZ",
      orderCta: "Objednat",
      formError: "Něco se nepovedlo. Zkuste to prosím znovu nebo nám zavolejte.",
      orderAria: "Objednat",
      voucherEyebrow: "DÁREK",
      voucherH: ["Chvíle klidu", "pro blízké lidi"],
      voucherHomeH2: "Dárkový poukaz",
      voucherHomeText: "Darujte hodinu klidu někomu blízkému. Vyberte masáž nebo částku — poukaz dorazí e-mailem do 24 hodin a platí 12 měsíců.",
      voucherCta: "Objednat dárkový poukaz",
      voucherMore: "Více o poukazu",
      fVoucherOption: "Dárkový poukaz",
    },
    facial: [
      { name: "Rituál pro obličej — krk, dekolt, obličej a hlava", desc: "Hluboká vícevrstvá procedura uvolňující svalové napětí, zlepšující krevní i lymfatický oběh a přirozeně obnovující tonus pleti.", min: 60, price: 1600 },
      { name: "Lymfatická masáž obličeje", desc: "Velmi jemná lymfodrenáž, která odvede otoky, zmenší váčky pod očima a zostří kontury obličeje.", min: 45, price: 1000 },
      { name: "Myofasciální masáž obličeje", desc: "Intenzivní práce s obličejovými svaly včetně vnitřní strany tváří. Modeluje konturu, redukuje nosoretní rýhy a povadlost.", min: 45, price: 1300 },
      { name: "Masáž krku, dekoltu a rukou", desc: "Zlepšuje prokrvení a lymfatickou drenáž a uvolňuje svaly krku a hrudníku.", min: 60, price: 1200 },
      { name: "Liftingová masáž", desc: "Redukuje otoky pod očima, zlepšuje lymfatickou drenáž a dodává obličeji lehčí, vypnutější vzhled.", min: 45, price: 1000 },
      { name: "Vakuová (baňková) masáž obličeje", desc: "Zaměřuje se na tonizaci a posílení svalů, zvyšuje pružnost pleti a zvýrazňuje kontury.", min: 45, price: 800 },
      { name: "Masáž Gua Sha", desc: "Drenážní a konturovací procedura, která uvolňuje napětí a zlepšuje tonus pleti tradičními technikami gua sha.", min: 45, price: 800 },
      { name: "Bukální masáž", desc: "Technika masáže obličeje prováděná zvenčí i přes ústní dutinu. Pomáhá uvolnit napětí svalů obličeje, zlepšit mikrocirkulaci, zvýšit tonus pleti a zpřesnit kontury obličeje. Podporuje přirozené omlazení a hlubokou relaxaci.", min: 30, price: 800 },
      { name: "Alginátová maska · doplněk", desc: "Zmírňuje otoky a zarudnutí, sjednocuje tón pleti, hloubkově hydratuje a zklidňuje.", min: 15, price: 250 },
      { name: "Masáž hlavy", desc: "Uvolňuje nervový systém, stimuluje růst vlasů, snižuje stres a pomáhá předcházet bolestem hlavy.", min: 30, price: 600 },
    ],
    body: [
      { name: "Sportovní masáž", desc: "Regenerace svalů po fyzické zátěži a intenzivním tréninku — uvolňuje napětí, zmírňuje bolestivost, urychluje zotavení.", min: 60, price: 1600 },
      { name: "Masáž bambusovými metličkami", desc: "Tělo je jemně prohřáto a masírováno bambusovými metličkami — zlepšuje oběh, tok lymfy i tonus pleti.", min: 60, price: 1600 },
      { name: "Lymfodrenážní masáž", desc: "Zlepšuje tok lymfy, zmírňuje otoky, podporuje metabolismus a celkovou pohodu.", min: 60, price: 1500 },
      { name: "Anticelulitidová masáž", desc: "Intenzivní práce na problémových partiích — zlepšuje prokrvení, stimuluje odbourávání tuku, zpevňuje pokožku.", min: 45, price: 1500 },
      { name: "Medová masáž", desc: "Přírodní med čistí pokožku a aktivuje metabolismus — pleť je hladší, jemnější a svěží.", min: 60, price: 1500 },
      { name: "Klasická masáž", desc: "Univerzální procedura pro relaxaci a celkovou pohodu — zlepšuje prokrvení a obnovuje energii.", min: 60, price: 1300 },
      { name: "Aroma masáž", desc: "Klasické techniky s individuálně vybranými esenciálními oleji — hluboce uvolňuje, snižuje stres, zlepšuje náladu.", min: 60, price: 1300 },
      { name: "Vakuová (baňková) masáž těla", desc: "Baňky aktivně stimulují krevní a lymfatický oběh — zmírňují otoky, působí proti celulitidě.", min: 45, price: 1200 },
      { name: "Masáž zad", desc: "Uvolňuje napětí ve svalech zad, zmírňuje bolest a únavu, zlepšuje prokrvení a přináší hlubokou relaxaci a pocit lehkosti v těle.", min: 30, price: 700 },
      { name: "Reflexní masáž chodidel", desc: "Technika působení na biologicky aktivní body a zóny těla spojené s vnitřními orgány a soustavami. Stimulace těchto bodů aktivuje přirozené procesy regenerace a celkové uvolnění organismu.", min: 30, price: 600 },
    ],
  },

  /* -------------------- РУССКИЙ -------------------- */
  ru: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\s/g, "\u00a0") + "\u00a0Kč",
    minLabel: "мин",
    strings: {
      navServices: "Услуги", navPrices: "Прайс-лист", navAbout: "Обо мне", navContact: "Контакты",
      heroEyebrow: "Massage 4 Beauty · Прага",
      heroH1: "Профессиональная студия массажа Прага 4",
      heroSub: "Здоровая, сияющая кожа начинается с нежного прикосновения. Массаж лица и тела от Людмилы — более десяти лет опыта, индивидуальные техники, заметный результат.",
      ctaBook: "Записаться", ctaPrices: "Смотреть прайс",
      aboutEyebrow: "Обо мне", aboutName: "Людмила Емельянова",
      aboutWelcome: "Добро пожаловать в Massage 4 Beauty.",
      aboutP1: "Меня зовут Людмила, и уже более десяти лет я помогаю своим клиентам находить гармонию, расслабление и естественную красоту с помощью профессионального массажа лица и тела.",
      aboutP2: "Каждая процедура уникальна и адаптируется к вашим индивидуальным потребностям. Независимо от того, ищете ли вы глубокое расслабление, облегчение напряжения, восстановление организма или естественное омоложение кожи, мы вместе подберём уход, который подойдёт именно вам.",
      aboutP3: "Моя цель — чтобы после процедуры вы уходили не только с ощущением лёгкости и отдыха, но и с новым зарядом энергии, более здоровой кожей и большей гармонией тела и души.",
      aboutCaption: "Сертифицированный массажист · Прага",
      pricesEyebrow: "Прайс-лист", pricesH2: "Процедуры и цены",
      groupFace: "Лицо", groupBody: "Тело",
      contactEyebrow: "Контакты", contactH2: "Запишитесь на визит",
      contactSub: "Напишите нам — поможем выбрать процедуру и удобное время визита.",
      lblAddress: "Адрес", lblPhone: "Телефон", lblEmail: "E-mail",
      fName: "Ваше имя", fContact: "Телефон или e-mail", fTreatment: "Процедура (по желанию)", fMessage: "Сообщение", fSend: "Отправить заявку",
      formThanks: "Спасибо! Мы скоро с вами свяжемся.",
      footerCopy: "© 2026 Beauty Massage · Людмила Емельянова",
      privacyLink: "Политика конфиденциальности",
      privacyEyebrow: "Правовая информация",
      privacyH1: "Политика конфиденциальности (GDPR)",
      privacyEffective: "Действует с 15 сентября 2026 года",
      privacyIntro: "Эта политика объясняет, какие персональные данные мы обрабатываем, когда вы посещаете сайт beautymassage.cz, отправляете нам заявку или связываетесь с нами другим способом, и какие у вас есть права.",
      privacyH2Controller: "1. Кто обрабатывает ваши данные",
      privacyController: "Контролёром персональных данных является Liudmyla Yemelianova (Людмила Емельянова), индивидуальный предприниматель, ИЧО 23110716, зарегистрированный адрес: Karlínské náměstí 170/3, 186 00 Praha 8 – Karlín. Под брендом Massage 4 Beauty она ведёт студию по адресу Děkanská vinice I 819/16, 140 00 Praha 4 – Nusle. С вопросами о защите данных обращайтесь по e-mail или телефону ниже.",
      privacyDpo: "Мы не назначали уполномоченного по защите персональных данных, так как для нас это не обязательно.",
      privacyH2Purposes: "2. Какие данные мы обрабатываем и зачем",
      privacyDtData: "Данные", privacyDtPurpose: "Цель", privacyDtBasis: "Правовое основание", privacyDtRetention: "Срок хранения",
      privacyH3Booking: "Заявка и запись",
      privacyBookingData: "Имя, телефон или e-mail, выбранная процедура и сообщение, которое вы нам пишете, а также данные из нашей переписки или разговора по телефону.",
      privacyBookingPurpose: "Ответить на заявку, согласовать время и провести массаж.",
      privacyBookingBasis: "Действия по вашему запросу до заключения договора и исполнение договора (ст. 6(1)(b) GDPR).",
      privacyBookingRetention: "Если запись не состоялась, мы удаляем данные не позднее чем через 12 месяцев после последнего контакта. Данные клиентов храним на протяжении сотрудничества и не более 3 лет после последнего визита; налоговые документы — в течение срока, установленного законом.",
      privacyBookingNote: "Пожалуйста, не указывайте в форме сведения о здоровье. Возможные ограничения по здоровью мы обсудим лично перед массажем.",
      privacyH3Spam: "Защита формы от спама",
      privacySpamData: "IP-адрес и технические данные о браузере и устройстве при отправке формы.",
      privacySpamPurpose: "Убедиться, что форму отправляет человек, и защитить нас от спама.",
      privacySpamBasis: "Законный интерес в защите формы от злоупотреблений (ст. 6(1)(f) GDPR).",
      privacySpamRetention: "Cloudflare обрабатывает данные только в течение времени, необходимого для проверки.",
      privacyH3Photos: "Фотографии",
      privacyPhotosData: "Фотографии или видео с процедуры.",
      privacyPhotosPurpose: "Примеры работ на сайте и в социальных сетях студии.",
      privacyPhotosBasis: "Ваше согласие (ст. 6(1)(a) GDPR), данное лично или письменно.",
      privacyPhotosRetention: "До отзыва согласия. После этого мы удалим фотографии с сайта и из наших профилей.",
      privacyH3Marketing: "Новости и предложения",
      privacyMarketingData: "E-mail или номер телефона.",
      privacyMarketingPurpose: "Отправлять новости, предложения и свободные даты по e-mail или SMS.",
      privacyMarketingBasis: "Ваше согласие (ст. 6(1)(a) GDPR).",
      privacyMarketingRetention: "До отзыва согласия, но не более 3 лет после последнего контакта.",
      privacyH3Analytics: "Аналитика посещаемости",
      privacyAnalyticsData: "Просмотренные страницы, нажатия на кнопки записи, телефона и e-mail, отправка заявки (без её содержания), тип устройства и браузера, приблизительное местоположение и онлайн-идентификаторы в файлах cookie. Google Analytics 4 не сохраняет ваш IP-адрес.",
      privacyAnalyticsPurpose: "Понять, как вы пользуетесь сайтом и какие страницы приводят к записи, и улучшать сайт.",
      privacyAnalyticsBasis: "Ваше согласие в баннере cookie (ст. 6(1)(a) GDPR и § 89(3) чешского закона № 127/2005 Sb. об электронных коммуникациях).",
      privacyAnalyticsRetention: "Не более 14 месяцев.",
      privacyAnalyticsNote: "Пока вы не дали согласие, Google Analytics не сохраняет файлы cookie и идентификаторы и получает лишь ограниченные сигналы, не связанные с вашим устройством (Google Consent Mode).",
      privacyH3Hosting: "Работа сайта",
      privacyHostingData: "IP-адрес и технические данные о браузере и запросе. Шрифты сайта загружаются из сервиса Google Fonts, поэтому при открытии страницы ваш IP-адрес передаётся и компании Google.",
      privacyHostingPurpose: "Доставить сайт и его шрифты и защитить сайт от атак.",
      privacyHostingBasis: "Законный интерес в безопасной и надёжной работе сайта (ст. 6(1)(f) GDPR).",
      privacyHostingRetention: "Технические записи хранятся недолго, согласно настройкам поставщиков.",
      privacyH2Recipients: "3. Кому мы передаём данные",
      privacyRecipientsIntro: "Мы не продаём ваши данные. С ними нам помогают следующие обработчики и поставщики услуг:",
      privacyRecipient1: "Cloudflare, Inc. (США) — хостинг сайта, безопасность и защита формы (Turnstile).",
      privacyRecipient2: "Google Ireland Limited / Google LLC — Google Analytics, Google Fonts и электронная почта (Gmail).",
      privacyRecipient3: "Telegram FZ-LLC (Объединённые Арабские Эмираты) — уведомления о новых заявках в мессенджере студии.",
      privacyRecipientsAuthorities: "Мы также можем передать данные государственным органам, если этого требует закон.",
      privacyH2Transfers: "4. Передача данных за пределы ЕС",
      privacyTransfers1: "Cloudflare и Google сертифицированы в рамках EU-U.S. Data Privacy Framework, поэтому на передачу данных этим компаниям в США распространяется решение Европейской комиссии об адекватном уровне защиты.",
      privacyTransfers2: "Telegram зарегистрирован в Объединённых Арабских Эмиратах, в отношении которых такого решения нет. Мы передаём туда сообщение с вашей заявкой, поскольку это необходимо для её обработки (ст. 49(1)(b) GDPR). Если вы этого не хотите, позвоните нам или напишите на e-mail вместо отправки формы.",
      privacyH2Storage: "5. Файлы cookie и хранилище браузера",
      privacyStorageIntro: "Необходимые данные мы сохраняем всегда, аналитические файлы cookie — только с вашего согласия. Если вы отказались от согласия или отозвали его, аналитические cookie больше не сохраняются.",
      privacyStorage1: "m4b-cookies — ваш выбор в баннере cookie (необходимо, хранится в браузере до удаления)",
      privacyStorage2: "m4b-lang — выбранный язык сайта (необходимо, хранится в браузере до удаления)",
      privacyStorage3: "_ga, _ga_XW10FL0HCW — файлы cookie Google Analytics для различения посетителей и визитов (аналитика, только с согласия, срок 2 года)",
      privacyStorage4: "Cloudflare Turnstile — технические данные, необходимые для проверки, что форму отправляет не робот (необходимо)",
      privacyCookieSettings: "Изменить настройки cookie",
      privacyH2Rights: "6. Ваши права",
      privacyRightsIntro: "Вы имеете право:",
      privacyRight1: "получить доступ к своим данным и их копию,",
      privacyRight2: "потребовать исправления неточных данных,",
      privacyRight3: "потребовать удаления данных,",
      privacyRight4: "потребовать ограничения обработки,",
      privacyRight5: "получить свои данные в машиночитаемом формате,",
      privacyRight6: "возразить против обработки на основании законного интереса,",
      privacyRight7: "в любой момент отозвать согласие; это не влияет на законность обработки до отзыва.",
      privacyRightsHow: "Напишите нам на beautymassage.prague@gmail.com. Мы ответим без неоправданной задержки, не позднее чем через месяц.",
      privacyComplaint: "Вы также можете подать жалобу в Управление по защите персональных данных Чехии (Úřad pro ochranu osobních údajů), Pplk. Sochora 727/27, 170 00 Praha 7 (uoou.gov.cz).",
      privacyH2Automated: "7. Автоматизированное принятие решений",
      privacyAutomated: "Мы не используем автоматизированное принятие решений или профилирование с юридическими или аналогично значимыми последствиями. Cloudflare Turnstile лишь автоматически проверяет, не отправляет ли форму робот; если проверка не удалась, позвоните нам или напишите на e-mail.",
      privacyH2Changes: "8. Изменения политики",
      privacyChanges: "Мы можем обновлять эту политику, например при смене используемых сервисов. Актуальная версия с датой вступления в силу всегда находится на этой странице.",
      cookieText: "Этот сайт использует файлы cookie для улучшения вашего опыта. Пожалуйста, выберите свои настройки.",
      cookieAccept: "Принять", cookieDecline: "Отклонить", cookieMore: "Политика конфиденциальности",
      crumbHome: "Главная",
      crumbServices: "Массажи",
      svcPhotoPlaceholder: "Место для баннера · 1920 × 800",
      svcFactDurationK: "Длительность",
      svcFactPriceK: "Цена",
      svcFactPlaceK: "Где",
      svcBookBtn: "Записаться",
      pricesHubLink: "Подробно о каждом массаже →",
      svcBookBtn2: "Записаться",
      voucherLabel: "ПОДАРОЧНЫЙ СЕРТИФИКАТ",
      orderCta: "Записаться",
      formError: "Что-то пошло не так. Попробуйте ещё раз или позвоните нам.",
      orderAria: "Записаться на",
      voucherEyebrow: "ПОДАРОК",
      voucherH: ["Минута покоя", "для близких людей"],
      voucherHomeH2: "Подарочный сертификат",
      voucherHomeText: "Подарите час покоя близкому человеку. Выберите массаж или сумму — сертификат придёт на почту за 24 часа и действует 12 месяцев.",
      voucherCta: "Заказать сертификат",
      voucherMore: "О сертификате",
      fVoucherOption: "Подарочный сертификат",
    },
    facial: [
      { name: "Ритуал для лица — шея, декольте, лицо и голова", desc: "Глубокая многоуровневая процедура: снимает мышечное напряжение, улучшает крово- и лимфообращение, естественно восстанавливает тонус кожи.", min: 60, price: 1600 },
      { name: "Лимфодренажный массаж лица", desc: "Очень мягкий дренаж, который убирает отёки, уменьшает мешки под глазами и делает контуры лица чётче.", min: 45, price: 1000 },
      { name: "Миофасциальный массаж лица", desc: "Интенсивная работа с мышцами лица, включая внутреннюю поверхность щёк. Моделирует контур, уменьшает носогубные складки и провисание.", min: 45, price: 1300 },
      { name: "Массаж шеи, декольте и рук", desc: "Улучшает кровоток и лимфодренаж, расслабляет мышцы шеи и грудного отдела.", min: 60, price: 1200 },
      { name: "Лифтинг-массаж", desc: "Уменьшает отёчность и «мешки» под глазами, улучшает лимфодренаж, придаёт лицу более лёгкий, подтянутый вид.", min: 45, price: 1000 },
      { name: "Вакуумный (баночный) массаж лица", desc: "Тонизирует и укрепляет мышцы, повышает упругость кожи и выразительность контуров.", min: 45, price: 800 },
      { name: "Массаж гуаша", desc: "Дренажный и контурирующий эффект: снимает напряжение и улучшает тонус кожи традиционными техниками гуаша.", min: 45, price: 800 },
      { name: "Буккальный массаж", desc: "техника массажа лица, выполняемая как снаружи, так и через ротовую полость. Помогает снять напряжение лицевых мышц, улучшить микроциркуляцию, повысить тонус кожи и сделать контуры лица более четкими. Способствует естественному омоложению и расслаблению.", min: 30, price: 800 },
      { name: "Альгинатная маска · дополнение", desc: "Снимает отёчность и покраснения, выравнивает тон, глубоко увлажняет и успокаивает кожу.", min: 15, price: 250 },
       { name: "Массаж головы", desc: "Расслабляет нервную систему, стимулирует рост волос, снижает стресс и помогает предотвращать головные боли.", min: 30, price: 600 },
    ],
    body: [
      { name: "Спортивный массаж", desc: "Восстановление мышц после нагрузок и интенсивных тренировок — снимает напряжение, уменьшает болезненность, ускоряет восстановление.", min: 60, price: 1600 },
      { name: "Массаж бамбуковыми вениками", desc: "Тело мягко прогревается и массируется бамбуковыми вениками — улучшаются кровообращение, лимфоток и тонус кожи.", min: 60, price: 1600 },
      { name: "Лимфодренажный массаж", desc: "Улучшает лимфоток, уменьшает отёки, поддерживает обмен веществ и общее самочувствие.",min: 60, price: 1500 },
      { name: "Антицеллюлитный массаж", desc: "Интенсивная работа с проблемными зонами — улучшает кровообращение, стимулирует расщепление жира, повышает упругость кожи.", min: 45, price: 1500 },
      { name: "Медовый массаж", desc: "Натуральный мёд очищает кожу и активизирует обмен веществ — кожа становится более гладкой, мягкой и свежей.", min: 60, price: 1500 },
      { name: "Классический массаж", desc: "Универсальная процедура для расслабления и общего оздоровления — улучшает кровообращение и восстанавливает силы.", min: 60, price: 1300 },
      { name: "Арома-массаж", desc: "Классические техники с индивидуально подобранными эфирными маслами — глубоко расслабляет, снижает стресс, улучшает настроение.", min: 60, price: 1300 },
      { name: "Вакуумный (баночный) массаж тела", desc: "Банки активно стимулируют крово- и лимфообращение — уменьшают отёки, борются с целлюлитом.", min: 45, price: 1200 },
      { name: "Массаж cпины", desc: "Снимает напряжение в мышцах спины, уменьшает боль и усталость, улучшает кровообращение и приносит глубокое расслабление и ощущение лёгкости в теле.", min: 30, price: 700 },
      { name: "Рефлекторный массаж стоп", desc: "Техника воздействия на биологически активные точки и зоны тела, которые связаны с внутренними органами и системами организма. Стимуляция этих точек  активизирует естественные процессы регенерации и общее расслабление организма.", min: 30, price: 600 },
    ],
  },
};
